export const metadata = {
  title:'Mohd Zafar',
  description:'Generated by Next.js',
  openGraph: {
    images: '/images/mz.jpg',
  },
 
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  ) 
}
