import SplashCursor from "@/component/animationContent/SplashCursor"

export const metadata = {
  title:'Mohd Zafar',
  description:'Generated by Next.js',
 
 
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <SplashCursor/>
        {children}
        </body>
    </html>
  ) 
}
