import SplashCursor from "@/component/animationContent/SplashCursor";
import Footer from "@/component/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mohd Zafar",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SplashCursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
